# Homework 1
### Set up the environment

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

### Q1. Pandas version

In [2]:
pd.__version__

'2.2.3'

#### Getting the data
The Laptops Price datase

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [4]:
data.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

### Q2. Records count

How many records are in the dataset?

In [5]:
data.shape[0]

2160

### Q3. Laptop brands

How many laptop brands are presented in the dataset?

In [6]:
data.Brand.nunique()

27

In [7]:
data.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

### Q4. Missing values

How many columns in the dataset have missing values?

In [8]:
data.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

### Q5. Maximum final price

What's the maximum final price of Dell notebooks in the dataset?

In [9]:
max_price = data[data.Brand == 'Dell']['Final Price'].max()
max_price

np.float64(3936.0)

### Q6. Median value of Screen

1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again.
Has it changed?

In [10]:
median_screen_value = data['Screen'].median()
median_screen_value

np.float64(15.6)

In [11]:
freq_screen_value = data['Screen'].mode()[0]
freq_screen_value

np.float64(15.6)

In [12]:
data['Screen'].fillna(median_screen_value).mode()[0]

np.float64(15.6)

In [13]:
data.Screen.median()

np.float64(15.6)

Values are the same irrespective of method

### Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the sum of all the elements of the result?

In [14]:
Innjoo_df = data[data.Brand =='Innjoo']             #Selecting all the "Innjoo" laptops from the dataset
Innjoo_df = Innjoo_df[['RAM', 'Storage', 'Screen']] #Selecting only columns RAM, Storage, Screen
Innjoo_df

      RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [15]:
X = Innjoo_df.values  #NumPy arrays of Innjoo laptop dataset
XTX = X.T.dot(X)      #matrix-matrix multiplication between the transpose of X and X

XTX_inv = np.linalg.inv(XTX)  #inverse of XTX
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [16]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [17]:
w = (XTX_inv@X.T)@y
w

array([45.58076606,  0.42783519, 45.29127938])

In [18]:
w.sum()

np.float64(91.2998806299555)